spring:
  application:
    name: SmsMessageMockingApp
  docker:
    compose:
      enabled: false

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 500            # 1분당 500회 호출 제한
        limitRefreshPeriod: 1m         # 1분 기준 (60초)
        timeoutDuration: 0             # 대기하지 않고 즉시 실패
    instances:
      kakaoApiLimiter:
        baseConfig: default            # 기본 설정을 따름

server:
  port: 8082
